### PR TITLE
TASK-98-Cycle Modal

### PR DESCRIPTION
**Pull request by fiardiel**
This task, I implemented the cycle modal, where it adds a cycle to the current user's ponds. It follows the criteria that it can add a cycle, list the ponds that the supervisor has, and set the start date which has 60 days difference with the end date (of course end date must be after the start date)

### CODE REVIEW

**Review by niboobin — APPROVED** [review]
Very good work rafi, I see that youre code is already solid and follows good practices, nice work!

**Review by rauloaul — APPROVED** [review]
## Overview

Hello Rafi, I already reviewed you code. It's already great, however there are a few improvement that could be implemented if you want

## Areas for Improvement

### 1. Error Message Display
The error handling logic in `AddCycleForm` could be improved to give the user more context, especially in network-related errors. Consider:
- Adding retries for network failures.
- Offering more detailed error messages to the user.

### 2. Testing Edge Cases
- **Date Validation:** Add tests for invalid date ranges (e.g., when the end date is earlier than the start date).
- **Missing Pond Data:** Include tests for cases where pond data is missing in `pond_fish_amount`.
- **UI Feedback:** Add test cases for UI-related feedback like:
  - Disabling buttons during submission.
  - Showing loading states for better user experience.

### 3. Code Duplication in Tests
There are some repetitive blocks in the test cases, particularly in:
- Rendering components.
- Mocking `fetchPonds`.

To improve readability, refactor these into helper functions to reduce duplication.

### 4. Consistency in Date Formatting
You're using `format` from `date-fns` to handle date formatting for the end date in the tests and form. Ensure that this approach is used consistently across the application for uniform date display.

### 5. Test Coverage
Ensure that the code coverage reports include crucial files and exclude only non-critical UI components, as mentioned in the `jest.config.ts`.

## Overall

The PR is well-structured and aligns with good testing practices. Minor improvements in error handling, test coverage, and code readability would make it even better. Keep up the great work!

**Comment by fiardiel** [comment]
> ## Overview
> Hello Rafi, I already reviewed you code. It's already great, however there are a few improvement that could be implemented if you want
> 
> ## Areas for Improvement
> ### 1. Error Message Display
> The error handling logic in `AddCycleForm` could be improved to give the user more context, especially in network-related errors. Consider:
> 
> * Adding retries for network failures.
> * Offering more detailed error messages to the user.
> 
> ### 2. Testing Edge Cases
> * **Date Validation:** Add tests for invalid date ranges (e.g., when the end date is earlier than the start date).
> * **Missing Pond Data:** Include tests for cases where pond data is missing in `pond_fish_amount`.
> * **UI Feedback:** Add test cases for UI-related feedback like:
>   
>   * Disabling buttons during submission.
>   * Showing loading states for better user experience.
> 
> ### 3. Code Duplication in Tests
> There are some repetitive blocks in the test cases, particularly in:
> 
> * Rendering components.
> * Mocking `fetchPonds`.
> 
> To improve readability, refactor these into helper functions to reduce duplication.
> 
> ### 4. Consistency in Date Formatting
> You're using `format` from `date-fns` to handle date formatting for the end date in the tests and form. Ensure that this approach is used consistently across the application for uniform date display.
> 
> ### 5. Test Coverage
> Ensure that the code coverage reports include crucial files and exclude only non-critical UI components, as mentioned in the `jest.config.ts`.
> 
> ## Overall
> The PR is well-structured and aligns with good testing practices. Minor improvements in error handling, test coverage, and code readability would make it even better. Keep up the great work!

Thank you for the feedback, Rafif. For number 2, it's all not possible since there is no input for end date, rather only inputting the start date and the test has proven that the end date will be always 60 days after the start. However, for the loading feedback I will add that later on since I agree with you it's a good UI feedback for the user. Also this block `{error || pondList.length === 0 ?` in the `AddCycleModal.tsx` file already checked if the pond data is missing. You made a pretty good point for number 3, I could shorten it by reducing duplicate codes. Thank you for the feedback, it quite helps the development process

**Comment by fiardiel** [comment]
I've changed the tests so that it reduces the duplication, if there are still anything to improve, feel free to let me know

**Comment by K24-github** [comment]
Hello rafi, the code looks great!

**Review by K24-github — APPROVED** [review]

**Pull request merged**
