### PR TITLE
Modified Read Food Sampling from mocking to using server actions 

### PR DESCRIPTION
**Pull request by niboobin**
In this pull request, i changed up the actions from using a mock data to an actual server action that fetches the get api from the backend and displays the food sampling data in the pond detail page. The reason why i used mock data the first time is because when i started working on the feature, the backend api is not implemented yet so i decided to use a mock first and then change it like this when the backend is already pushed to the repo.

Another thing to add here, is that I already pulled Kevins code and cleared up all the merge conflicts that we had :) so i think for now all the errors is all fixed.

### CODE REVIEW

**Comment by niboobin** [comment]
as for the issues that have appeared, im working to fix them now

**Comment by niboobin** [comment]
kay its fixed

**Review by fiardiel — APPROVED** [review]
Good job, Obin!

**Review by K24-github — APPROVED** [review]
Looks great obin! good job

**Pull request merged**
