### PR TITLE
Task 120 profile page

### PR DESCRIPTION
**Pull request by raisaafadilla**
I’ve created a profile page. You can access it by clicking the profile on the sidebar or by navigating to the route /profile/[phonenumber]. The page displays the user’s first name, last name, phone number, and image (currently shown by image name). The tests also cover 100%.

### CODE REVIEW

**Review by fiardiel — DISMISSED** [review]
Hello Raisa, I see that you have created the implementation of the profile page. You have correctly fetched the profile on the server component. However, there are several problems in the code.  There is a display of the `image_name`, which shouldn't be like that, you should display the image instead of the name, however since there is no image cloud container yet, if you display a blank image its fine. I already have uploaded a dummy image in the `public/` directory. Also you shouldn't delete the page.tsx since I implemented the update profile in that page which creates conflict

**Comment by fiardiel** [comment]
You need to merge the conflicts first before merging the code, I think the new code looks fine

**Review by fiardiel — APPROVED** [review]
Good job, Raisa! I see that you have solved the merge conflicts. Well done.

**Review by rauloaul — APPROVED** [review]
Good Job on solving the conflict, raisa!

**Review by niboobin — APPROVED** [review]
Great job on implementing the profile page and solving the merge conflicts!

**Pull request merged**
